server:
  port: 8888

spring:
  datasource:
    url: jdbc:h2:mem:AZ;INIT=CREATE SCHEMA IF NOT EXISTS sts;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;NON_KEYWORDS=VALUE
    username: db_user
    password: db_user@123
  jpa:
    show-sql: false
    properties:
      hibernate:
        default_schema: sts
  flyway:
    enabled: false
    locations:
    - db/migration/flyway/h2
  liquibase:
    enabled: true
    change-log: classpath:/db/migration/liquibase/changelog.yml
    default-schema: public

sts:
  secret-server-client:
    audience: moped-client
    secret-server-uri: http://localhost:8885/secret-server/token-exchange
    cache:
      enabled: true
      maximum-size: 1000
      expire-after-access: 10
  resource-server-management:
    resource-retriever:
      http-connect-timeout: 10000
      http-read-timeout: 60000
      http-size-limit: 512000
    resource-servers:
    - audience: "sts"
      jwks-url: "http://localhost:8887/pop"
    - audience: "sts-service-component-example"
      jwks-url: "http://localhost:8887/pop"
    - audience: "sts-service-component"
      jwks-url: "http://sts-service-component:8887/service-component/pop"
  persistence:
    lock-expiry: 30000
  keymanagement:
    rotation:
      check-interval: 60000
      enc-key-pairs:
        min-keys: 5
        enabled: true
      sign-key-pairs:
        min-keys: 5
        enabled: true
      secret-keys:
        min-keys: 5
        enabled: true
    persistence:
      container-name: adsts-container
      password: ahDa5cahda1ooxahh8aikaeChiePaeKa
    keystore:
      password: LuYie2eebebahNgoopiehaiV9wis7anu
      type: UBER
      name: sts-example-keystore
      alias-prefix: sts-example-
      keys:
        enc-key-pairs:
          initial-count: 5
          algo: RSA
          sig-algo: SHA256withRSA
          size: 2048
          name: Adorsys Security Token Service
          validity-interval: 3600000
          legacy-interval: 86400000
        sign-key-pairs:
          initial-count: 5
          algo: RSA
          sig-algo: SHA256withRSA
          size: 2048
          name: Adorsys Security Token Service
          validity-interval: 3600000
          legacy-interval: 86400000
        secret-keys:
          initial-count: 5
          algo: AES
          size: 256
          validity-interval: 3600000
          legacy-interval: 86400000
