version: '3.1'
services:
  keycloak:
    build: ./keycloak-storage-provider
    image: "local/keycloak-sts-adapter:latest"
    environment:
      KEYCLOAK_PASSWORD: admin123
      KEYCLOAK_USER: admin
    ports:
      - "8080:8080"
      - "8787:8787"
    command:
      - "-b"
      - "0.0.0.0"
      - "--debug"
    networks:
      - sts_network
  post_process:
    image: adorsys/keycloak-config-cli:v0.5.1-1-5.0.0
    volumes:
      - ./keycloak-config/dev:/tmp/keycloak-config-cli/configs
    environment:
      - KEYCLOAK_URL=http://keycloak:8080/auth
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin123
      - WAIT_TIME_IN_SECONDS=120
      - SPRING_PROFILES_INCLUDE=debug
    command: config-cli
    networks:
      - sts_network
  sts-mongo:
    image: mongo:3.6.5
    container_name: sts_mongo
    environment:
      MONGO_INITDB_DATABASE: sts
    volumes:
      - "./.docker/sts-mongo:/data/db"
    ports:
      - 27017:27017
    command: --smallfiles
    networks:
      - sts_network

networks:
  sts_network:
