services:
  keycloak:
    build: ./keycloak-storage-provider
    image: "local/keycloak-sts-adapter:latest"
    environment:
      KEYCLOAK_PASSWORD: admin123
      KEYCLOAK_USER: admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
    ports:
      - "8180:8080"
      - "8787:8787"
    command:
      - "start-dev"
    networks:
      - sts_network
  post_process:
    image: adorsys/keycloak-config-cli:5.12.0-22.0.4
    volumes:
      - ./keycloak-config/dev:/config
    environment:
      KEYCLOAK_PASSWORD: admin123
      KEYCLOAK_USER: admin
      KEYCLOAK_URL: http://keycloak:8080/
      KEYCLOAK_ADMIN : admin
      KEYCLOAK_ADMIN_PASSWORD : admin123
      KEYCLOAK_AVAILABILITYCHECK_ENABLED: true
      IMPORT_FILES_LOCATIONS: /config/*
      SPRING_PROFILES_INCLUDE : debug
    command: config-cli
    networks:
      - sts_network

  sts-mongo:
    image: mongo:7.0.7
    container_name: sts_mongo
    environment:
      MONGO_INITDB_DATABASE: sts
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodata:/data/db"
    ports:
      - 27017:27017
    networks:
      - sts_network

volumes:
  mongodata:

networks:
  sts_network:
