version: '3.1'
services:
  keycloak:
    build: ./keycloak-storage-provider
    image: "local/keycloak-sts-adapter:latest"
    environment:
      KEYCLOAK_PASSWORD: admin123
      KEYCLOAK_USER: admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
    ports:
      - "8080:8080"
      - "8787:8787"
    command:
      - "start-dev"
    networks:
      - sts_network
  post_process:
    image: adorsys/keycloak-config-cli:5.7.0-21.1.1
    volumes:
      - ./keycloak-config/dev:/config
    environment:
      KEYCLOAK_PASSWORD: admin123
      KEYCLOAK_USER: admin
      KEYCLOAK_URL: http://keycloak:8080
      KEYCLOAK_ADMIN : admin
      KEYCLOAK_ADMIN_PASSWORD : admin123
      WAIT_TIME_IN_SECONDS : 120
      SPRING_PROFILES_INCLUDE : debug
    command: config-cli
    networks:
      - sts_network

  sts-mongo:
    image: mongo:6.0.8
    container_name: sts_mongo
    environment:
      MONGO_INITDB_DATABASE: sts
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - "./.docker/sts-mongo:/data/db"
    ports:
      - 27017:27017
    networks:
      - sts_network

networks:
  sts_network:
