services:
  keycloak:
    image: adorsys/keycloak-sts-adapter:latest
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      DEBUG: 'true'
      DEBUG_PORT: '*:8787'
    ports:
      - "8180:8180"
      - "8787:8787"
    command:
      - "start-dev"
      - "--http-port=8180"
    networks:
      - sts_network

  post_process:
    image: adorsys/keycloak-config-cli:6.1.5-25.0.1
    volumes:
      - ./keycloak-config:/config
    environment:
      KEYCLOAK_PASSWORD: admin123
      KEYCLOAK_USER: admin
      KEYCLOAK_URL: http://keycloak:8180/
      KEYCLOAK_AVAILABILITYCHECK_ENABLED: true
      IMPORT_FILES_LOCATIONS: /config/*
      SPRING_PROFILES_INCLUDE: debug
      IMPORT_VARSUBSTITUTION_ENABLED: true
      LOGIN_URL: http://host.docker.internal:8887/login # ip address of host accessible from within container (for example 172.17.0.1)
    command: config-cli
    networks:
      - sts_network

  sts-mongo:
    image: mongo:7.0.7
    container_name: sts_mongo
    environment:
      MONGO_INITDB_DATABASE: sts
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017
    networks:
      - sts_network

  sts:
    image: adorsys/sts-example:latest
    networks:
      - sts_network
    environment:
      - SPRING_PROFILES_ACTIVE=mongo
      - SPRING_DATA_MONGODB_DATABASE=sts
      - SPRING_DATA_MONGODB_URI=mongodb://sts-mongo/sts
      - logging_level_de_adorsys_sts_keyrotation_KeyRotationSchedule=debug
      - sts_secret-server-client_audience=moped-client
      - sts_secret-server-client_secret-server-uri=http://sts-secret-server:8080/secret-server/token-exchange
      - sts_secret-server-client_cache_enabled=true
      - sts_secret-server-client_cache_maximum-size=1000
      - sts_secret-server-client_cache_expire-after-access=10
      - sts_authservers_0_name=local keycloak
      - sts_authservers_0_iss-url=http://localhost:8080/auth/realms/moped
      - sts_authservers_0_jwks-url=http://keycloak:8080/auth/realms/moped/protocol/openid-connect/certs
      - sts_authservers_1_name=secret-server
      - sts_authservers_1_iss-url=http://sts-secret-server:8080
      - sts_authservers_1_jwks-url=http://sts-secret-server:8080/pop
      - sts_resource-server-management_resource-retriever_http-connect-timeout=10000
      - sts_resource-server-management_resource-retriever_http-read-timeout=60000
      - sts_resource-server-management_resource-retriever_http-size-limit=512000
      - sts_resource-server-management_resource-servers_0_audience=sts
      - sts_resource-server-management_resource-servers_0_jwks-url=http://localhost:8888/pop
      - sts_resource-server-management_resource-servers_1_audience=sts-service-component
      - sts_resource-server-management_resource-servers_1_jwks-url=http://sts-service-component:8887/pop
    ports:
      - "8888:8888"

  sts-service-component:
    image: adorsys/sts-service-component-example:latest
    ports:
      - "8887:8887"
    environment:
      - sts_audience_name=sts-service-component
      - SPRING_PROFILES_ACTIVE=mongo
      - SPRING_DATA_MONGODB_DATABASE=sts
      - SPRING_DATA_MONGODB_URI=mongodb://sts-mongo/sts
      - logging_level_de_adorsys_sts_keyrotation_KeyRotationSchedule=debug
      - sts_authservers_0_name=local keycloak
      - sts_authservers_0_iss-url=http://localhost:8080/auth/realms/moped
      - sts_authservers_0_jwks-url=http://keycloak:8080/auth/realms/moped/protocol/openid-connect/certs
    networks:
      - sts_network

  sts-service-component_2:
    image: adorsys/sts-service-component-example:latest
    ports:
      - "8886:8887"
    environment:
      - sts_audience_name=sts-service-component
      - SPRING_PROFILES_ACTIVE=mongo
      - SPRING_DATA_MONGODB_DATABASE=sts
      - SPRING_DATA_MONGODB_URI=mongodb://sts-mongo/sts
      - logging_level_de_adorsys_sts_keyrotation_KeyRotationSchedule=debug
      - sts_authservers_0_name=local keycloak
      - sts_authservers_0_iss-url=http://localhost:8080/auth/realms/moped
      - sts_authservers_0_jwks-url=http://keycloak:8080/auth/realms/moped/protocol/openid-connect/certs
    networks:
      - sts_network

  sts-client:
    image: adorsys/sts-client-example:latest
    environment:
      - NG_KEYCLOAK_AUTH_URL=http://localhost:8080/auth
      - NG_KEYCLOAK_REALM=moped
      - NG_KEYCLOAK_CLIENT_ID=moped-client
      - NG_KEYCLOAK_SCOPE=sts-service-component
      - NG_SERVICE_URL=http://localhost:8887/helloworld
      - NG_SECRET_URL=http://localhost:8888/secret
    networks:
      - sts_network
    ports:
      - 8090:8080

  sts-secret-server:
    image: adorsys/sts-secret-server:latest
    networks:
      - sts_network
    environment:
      - SPRING_PROFILES_ACTIVE=mongo
      - SPRING_DATA_MONGODB_DATABASE=sts
      - SPRING_DATA_MONGODB_URI=mongodb://sts-mongo/sts
      - sts_secret-server_secret-length=8192
      - sts_secret-server_endpoint=/secret-server/token-exchange
      - sts_secret-server_encryption_enabled=true
      - sts_secret-server_encryption_algorithm=A256GCMKW
      - sts_secret-server_encryption_encryption-method=A256GCM
      - sts_secret-server_encryption_key={"kty":"oct","k":"7KmFL-k9Sib6Llt4CZnwHfxjIfAgbAbOdwbemIGhO6U"}
      - sts_authservers_0_name=local keycloak
      - sts_authservers_0_iss-url=http://localhost:8080/auth/realms/moped
      - sts_authservers_0_jwks-url=http://keycloak:8080/auth/realms/moped/protocol/openid-connect/certs
      - sts_resource-server-management_resource-retriever_http-read-timeout=60000
      - sts_resource-server-management_resource-retriever_http-size-limit=512000
      - sts_resource-server-management_resource-retriever_cache_enabled=true
      - sts_resource-server-management_resource-retriever_cache_maximum-size=1000
      - sts_resource-server-management_resource-retriever_cache_expire-after-access=10
      - sts_resource-server-management_resourceservers_0_audience=moped-client
      - sts_resource-server-management_resourceservers_0_jwks-url=http://sts:8888/pop
      - sts_keymanagement_keystore_password=NiPae6AiOoto2Eeyaode9LeeOhngi4Ao
    ports:
      - "8885:8080"

volumes:
  mongodata:

networks:
  sts_network:
