version: '2.0'
services:
  keycloak:
    image: "jboss/keycloak:${keycloak.version}"
    environment:
      KEYCLOAK_PASSWORD: admin123
      KEYCLOAK_USER: admin
    ports:
    - "8080:8080"
    - "8787:8787"
    command:
    - "-b"
    - "0.0.0.0"
    - "--debug"
    networks:
    - it_sts_network

  post_process:
    image: "adorsys/keycloak-config-cli:v0.5.1-1-${keycloak.version}"
    volumes:
    - ./src/test/docker:/tmp/keycloak-config-cli/configs
    environment:
    - KEYCLOAK_URL=http://keycloak:8080/auth
    - KEYCLOAK_ADMIN=admin
    - KEYCLOAK_ADMIN_PASSWORD=admin123
    - WAIT_TIME_IN_SECONDS=300
    networks:
    - it_sts_network

networks:
  it_sts_network:
