spring:
  flyway:
    enabled: false
  liquibase:
    enabled: false
  data:
    mongodb:
      host: localhost
      port: 27017
      database: sts
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
