spring:
  profiles:
    include: jpa

  liquibase:
    default-schema: false
    change-log: classpath:db/migration/liquibase/changelog.yml
    enabled: true

  flyway:
    locations:
    - classpath:/db/migration/flyway/h2
    enabled: false

  datasource:
    url: jdbc:h2:./sts;INIT=CREATE SCHEMA IF NOT EXISTS sts;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
