spring:
  profiles:
    include: jpa

  liquibase:
    default-schema: public

  flyway:
    locations:
    - db/migration/flyway/h2

  datasource:
    url: jdbc:h2:./sts_h2_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
