spring:
  liquibase:
    default-schema: sts
  flyway:
    locations:
    - classpath:/db/migration/flyway/postgres

  datasource:
    url: jdbc:postgresql://localhost:5432/sts
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
