spring:
  liquibase:
    default-schema: public

  flyway:
    locations:
    - db/migration/flyway/postgres

  datasource:
    url: jdbc:postgresql://localhost:5432/sts
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    properties.hibernate.temp.use_jdbc_metadata_defaults: false

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
