spring:
  liquibase:
    default-schema: sts

  flyway:
    locations:
    - classpath:/db/migration/flyway/mysql

  datasource:
    url: jdbc:mysql://localhost:3306/sts?serverTimezone=UTC
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
