spring:
  liquibase:
    default-schema: sts

  flyway:
    locations:
    - db/migration/flyway/mysql

  datasource:
    url: jdbc:mysql://localhost:3306/sts
  jpa:
    database-platform: org.hibernate.dialect.MySQLInnoDBDialect
    hibernate.use-new-id-generator-mappings: false

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
