spring:
  profiles:
    include: jpa

  liquibase:
    default-schema: sts

  flyway:
    locations:
    - classpath:/db/migration/flyway/mysql

  datasource:
    url: jdbc:mysql://localhost:3306/sts
  jpa:
    database-platform: org.hibernate.dialect.MySQLInnoDBDialect
    hibernate.use-new-id-generator-mappings: false
