spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    generate-ddl: true

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
