spring:
  liquibase:
    default-schema: public

  flyway:
    locations:
    - classpath:/db/migration/flyway/h2

  datasource:
    url: jdbc:h2:./sts_h2_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS sts;NON_KEYWORDS=VALUE
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
