name: DockerHub
on:
  workflow_call:

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifacts

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: sts-client-example

#      TODO delete this step after successful testing
      - name: Display structure of downloaded files
        run: ls -R

      - name: Get the tag name
        # temporarily
#        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
        run: echo "TAG=v1.1.29" >> $GITHUB_ENV

      - name: Build and push 'sts-example' docker image
        uses: docker/build-push-action@v6
        with:
          context: ./sts-example
          platforms: linux/amd64,linux/arm64
          push: true
          provenance: false
          tags: |
            adorsys/sts-example:${{ env.TAG }}
            adorsys/sts-example:latest

      - name: Build and push 'sts-service-component-example' docker image
        uses: docker/build-push-action@v6
        with:
          context: ./sts-service-component-example
          platforms: linux/amd64,linux/arm64
          push: true
          provenance: false
          tags: |
            adorsys/sts-service-component-example:${{ env.TAG }}
            adorsys/sts-service-component-example:latest

      - name: Build and push 'sts-client-example' docker image
        uses: docker/build-push-action@v6
        with:
          context: ./sts-client-example
          platforms: linux/amd64,linux/arm64
          push: true
          provenance: false
          tags: |
            adorsys/sts-client-example:${{ env.TAG }}
            adorsys/sts-client-example:latest

      - name: Build and push 'sts-secret-server' docker image
        uses: docker/build-push-action@v6
        with:
          context: ./sts-secret-server
          platforms: linux/amd64,linux/arm64
          push: true
          provenance: false
          tags: |
            adorsys/sts-secret-server:${{ env.TAG }}
            adorsys/sts-secret-server:latest

      - name: Build and push 'keycloak-sts-adapter' docker image
        uses: docker/build-push-action@v6
        with:
          context: ./keycloak-storage-provider
          platforms: linux/amd64,linux/arm64
          push: true
          provenance: false
          tags: |
            adorsys/keycloak-sts-adapter:${{ env.TAG }}
            adorsys/keycloak-sts-adapter:latest
