name: Frontend build
on:
  workflow_call:

jobs:

  build_node:
    name: Build & Test frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sts-client-example
    steps:
      - name: Step 1 - Checkout repository code
        uses: actions/checkout@v4
        with:
          sparse-checkout: 'sts-client-example'
          sparse-checkout-cone-mode: false

      - name: Step 2 - setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - run: npm run prod

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            ${{ github.workspace }}/sts-client-example/dist
            ${{ github.workspace }}/sts-client-example/docker/create_env.json.sh
          overwrite: false
          if-no-files-found: error