name: Actions on pull requests
on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  build-java:
    name: Build & Test backend
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Checkout repository code
        uses: actions/checkout@v4

      - name: Step 2 - Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Step 3 - Build & Test
        run: mvn clean verify -ntp

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            ${{ github.workspace }}/**/*.jar
            ${{ github.workspace }}/**/Dockerfile
          overwrite: false
          if-no-files-found: error

      - name: Step 4 - Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

  build-frontend:
    uses: ./.github/workflows/frontend.yml
    secrets: inherit
