name: Actions on pull requests
on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  build_java:
    name: Build & Test backend
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Checkout repository code
        uses: actions/checkout@v4

      - name: Step 2 - Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Step 3 - Build & Test
        run: mvn clean verify -ntp

      - name: Step 4 - Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

  build_angular:
    name: Build & Test frontend
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Checkout repository code
        uses: actions/checkout@v4

      - name: Step 2 - setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci
      - run: npm run prod