name: Develop branch build
on:
  push:
    branches:
      - develop

jobs:
  Develop-Branch-Build:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Checkout repository code
        uses: actions/checkout@v4

      - name: Step 2 - Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Step 3 - Build & Test
        run: mvn clean verify -ntp

      - name: Step 5 - Build client
        run: ./scripts/build_client.sh

      - name: Maven deploy snapshot
        run: ./scripts/mvn_deploy.sh
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_EXECUTABLE: gpg
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
          GPG_OWNERTRUST: ${{ secrets.GPG_OWNERTRUST }}
