on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: "Version to release"

name: Release

jobs:
  release_workflow:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Step 1 - Checkout repository code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          fetch-depth: 0
          token: ${{ secrets.PUSH_TO_PROTECTED_BRANCH }}

      - name: Step 2 - Run release-scripts
        env:
          VERSION: ${{ inputs.version }}
          GITHUB_TOKEN: ${{ secrets.PUSH_TO_PROTECTED_BRANCH }}
        run: |
          NEXT_VERSION="$(echo '${{ inputs.version }}' | perl -pe 's{^(([0-9]\.)+)?([0-9]+)$}{$1 . ($3 + 1)}e')"
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          ./release-scripts/release.sh -v $VERSION $NEXT_VERSION
          echo $(git log -5 --oneline)
          git push --atomic origin master develop --follow-tags # all or nothing

      - name: Step 3 - Create release notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG="$(git describe --abbrev=0)"
          echo $TAG
          gh release create "$TAG" --repo="$GITHUB_REPOSITORY" --title="${GITHUB_REPOSITORY#*/} ${TAG#v}" --generate-notes
